jobs:
  action:
    name: Ci
    runs-on: ubuntu-20.04

    steps:
      - name: Pull Code
        uses: actions/checkout@v2
      - name: Fetch Deps
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Test
        run: ./main/action

name: Ci

on:
  schedule:
    - cron: "45 0/3 * * *"
